name: Latest posts workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: khaosdoctor/blog-post-workflow@master
        with:
          comment_tag_name: BEHANCE
          feed_list: "https://www.behance.net/feeds/user?username=iftakhar"